config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                 Controller#Action
# recipes_index GET    /recipes/index(.:format)    recipes#index
#       recipes GET    /recipes(.:format)          recipes#index
#               POST   /recipes(.:format)          recipes#create
#    new_recipe GET    /recipes/new(.:format)      recipes#new
#   edit_recipe GET    /recipes/:id/edit(.:format) recipes#edit
#        recipe GET    /recipes/:id(.:format)      recipes#show
#               PATCH  /recipes/:id(.:format)      recipes#update
#               PUT    /recipes/:id(.:format)      recipes#update
#               DELETE /recipes/:id(.:format)      recipes#destroy
#          root GET    /                           recipes#index
# 

Rails.application.routes.draw do

  get 'recipes/index'
    resources :recipes

  root 'recipes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixin.rb
# == Schema Information
#
# Table name: fixins
#
#  id         :integer          not null, primary key
#  name       :string
#  amount     :string
#  recipe_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Fixin < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Recipe < ApplicationRecord
  has_many :fixins, inverse_of: :recipe, :dependent => :delete_all
  has_many :steps, inverse_of: :recipe, :dependent => :delete_all
  accepts_nested_attributes_for :fixins, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true
end

app/models/step.rb
# == Schema Information
#
# Table name: steps
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  recipe_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Step < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fixins_controller.rb
class FixinsController < ApplicationController

def new
@fixins = Fixin.all
end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
     @recipes = Recipe.page(params[:page]).per(5)
  end

  def show
     @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    # @recipe.fixins.build
    # @recipe.steps.build
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(rec_params)
    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(rec_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  private
    def rec_params
      params.require(:recipe).permit(:name, :description, fixins_attributes: [:id, :name, :amount, :_destroy], steps_attributes: [:id, :title, :description, :_destroy])
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fixins_helper.rb
module FixinsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/fixins/edit.html.haml
<h1>Fixins#edit</h1>
<p>Find me in app/views/fixins/edit.html.erb</p>

app/views/fixins/new.html.haml
<h1>Fixins#new</h1>
<p>Find me in app/views/fixins/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipebox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_fixin_fields.html.haml
.nested-fields
  %br
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :amount
    %br
    = f.text_field :amount
  = link_to_remove_association "remove fixin", f

app/views/recipes/_form.html.haml
= form_for @recipe do |f|
  #error_explanation{:style => "display:none;"}
    %ul
      - if @recipe.errors.any?
        - @recipe.errors.full_messages.each do |msg|
          %li= msg
  .fields
    = f.label :Name
    %br/
    = f.text_field :name
    %br/
    = f.label :Description
    %br/
    = f.text_field :description
    %br/
    %br
    %h2 Ingredients



    #fixins
      = f.fields_for :fixins do |fixin|
        = render 'fixin_fields', f: fixin
    .links
      = link_to_add_association 'add fixin', f, :fixins, 'data-association-insertion-method' => 'append'

    %h2 Prep Steps


    #steps
      = f.fields_for :steps do |step|
        = render 'step_fields', f: step
    .links
      = link_to_add_association 'add step', f, :steps, 'data-association-insertion-method' => 'append'
      %br
    %br
    = f.submit
    %br

.success-message

app/views/recipes/_step_fields.html.haml
.nested-fields
%br
  .field
    = f.label :Title
    %br
    = f.text_field :title
  .field
    = f.label :Description
    %br
    = f.text_field :description
  = link_to_remove_association "remove step", f

app/views/recipes/edit.html.haml
%h1 Editing this recipe.
= render 'form'
= link_to 'Back', recipes_path, :class => "backbutton"

app/views/recipes/index.html.haml
%h1 Recipe
= link_to 'Add a new recipe to the Recipebox!', new_recipe_path, :class => "toplink"
%br
%table.table
  %tr.headrow
    %th.tabhead Name
    %th.tabhead Description

  - @recipes.each do |recipe|
    %tr
      %td= recipe.name
      %td= recipe.description
      %td= link_to 'Show this Recipe', recipe_path(recipe)
      %td= link_to 'Edit this Recipe', edit_recipe_path(recipe)
      %td= link_to 'Delete this Recipe', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure you want to delete this recipe?' }
%br
  = paginate @recipes

app/views/recipes/new.html.haml
%h1 Adding a new recipe!
= render 'form'
%br
= link_to 'Back', recipes_path, :class => "backbutton"

app/views/recipes/show.html.haml
%p.show
  %strong Name:
  = @recipe.name
%p.show
  %strong Description:
  = @recipe.description
%p.show
  %strong Ingredients
  - @recipe.fixins.each do |i|
    %li= i.name + " +++ " + i.amount
%p.show
  %strong Steps
  - @recipe.steps.each do |i|
    %li= i.title + " +++ " + i.description

-# %h2 Comments
-# = render @article.comments
-# %h2 Add a comment:
-# = render 'comments/form'

= link_to 'Edit this recipe', edit_recipe_path(@recipe), :class => "editbutton"
%br
= link_to 'Back', recipes_path, :class => "backbutton"

app/views/steps/edit.html.haml
<h1>Steps#edit</h1>
<p>Find me in app/views/steps/edit.html.erb</p>

app/views/steps/index.html.haml
<h1>Steps#index</h1>
<p>Find me in app/views/steps/index.html.erb</p>

app/views/steps/new.html.haml
<h1>Steps#new</h1>
<p>Find me in app/views/steps/new.html.erb</p>